"""updated about in database to about_me

Revision ID: 316a8dcc8522
Revises: 6ce5bb15478b
Create Date: 2021-09-13 00:40:32.114975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '316a8dcc8522'
down_revision = '6ce5bb15478b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=128), nullable=True))
    op.drop_column('user', 'about')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about', sa.VARCHAR(length=128), nullable=True))
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
